sudo: required
language: generic
dist: xenial

matrix:
  include:
    - name: "Xenial kinetic"
    - env: ROS_DISTRO=kinetic

services:
  - docker

script:
  - echo $ROS_DISTRO
  - docker build -f ./docker/$ROS_DISTRO/Dockerfile .
